# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#0C1E30'
foreground='#fdfdfd'
cursor='#ff0000'

# Colors
color0='#2C3E50'
color1='#1ABC9C'
color2='#E74C3C'
color3='#1ABC9C'
color4='#E74C3C'
color5='#3498DB'
color6='#E74C3C'
color7='#fdfdfd'
color8='#95A5A6'
color9='#1ABC9C'
color10='#E74C3C'
color11='#1ABC9C'
color12='#E74C3C'
color13='#3498DB'
color14='#E74C3C'
color15='#FEF4F7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
