# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#021b21'
foreground='#e8dfd6'
cursor='#ef5847'

# Colors
color0='#032c36'
color1='#c2454e'
color2='#7cbf9e'
color3='#8a7a63'
color4='#2e3340'
color5='#ff5879'
color6='#44b5b1'
color7='#f2f1b9'
color8='#065f73'
color9='#c2454e'
color10='#7cbf9e'
color11='#8a7a63'
color12='#2e3340'
color13='#ff5879'
color14='#44b5b1'
color15='#f2f1b9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
