# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1F1F1F'
foreground='#C0B18B'
cursor='#AC5D2F'

# Colors
color0='#4A3637'
color1='#D17B49'
color2='#7B8748'
color3='#AF865A'
color4='#535C5C'
color5='#775759'
color6='#6D715E'
color7='#C0B18B'
color8='#7e5c5e'
color9='#D17B49'
color10='#7B8748'
color11='#AF865A'
color12='#535C5C'
color13='#775759'
color14='#6D715E'
color15='#C0B18B'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
